'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import Script from 'next/script'
import Link from 'next/link'
import type { User } from '@supabase/supabase-js'

const ANGLES = ['Hot Take', 'Balanced', "Devil's Advocate", 'Contrarian', 'Expert Analysis']
const ANGLE_ICONS: Record<string, string> = {
  'Hot Take': '🔥',
  'Balanced': '⚖️',
  "Devil's Advocate": '😈',
  'Contrarian': '↩️',
  'Expert Analysis': '🎓',
}
const ANGLE_COLORS: Record<string, string> = {
  'Hot Take': '#e85d3a',
  'Balanced': '#3a7bd5',
  "Devil's Advocate": '#7c3aed',
  'Contrarian': '#d97706',
  'Expert Analysis': '#059669',
}

const TRENDING_TOPICS = [
  'AI & Jobs', 'Bitcoin', 'Remote Work', 'Social Media', 'UBI',
  'College Degrees', 'Cancel Culture', 'Climate Change', '4-Day Week', 'Crypto'
]

const HOME_FAQS = [
  { q: 'Is Thought of View free?', a: 'Yes — free accounts get 5 takes per day across all angles. Premium members get unlimited takes, no ads, and priority generation.' },
  { q: 'What is the Daily Battle?', a: 'Every day, two AI perspectives debate a new topic. Vote for who you think won, then see how the community voted and what the AI judge decided.' },
  { q: 'Do I need an account?', a: 'No account needed to generate takes or vote. Sign in with Google to save takes to the public feed, upvote, and comment.' },
  { q: 'How are the takes generated?', a: 'Takes are generated by AI language models via the Groq API. Each angle is prompted differently to produce a distinct, argued perspective on your topic.' },
  { q: 'Can I trust the takes?', a: 'Takes are sharp opinions, not factual summaries. They\'re great for debate prep, understanding viewpoints, and exploring arguments. Always verify facts independently.' },
]

type Take = {
  id: string
  topic: string
  angle: string
  headline: string
  body: string
  upvotes: number
}

type DailyBattleMsg = { speaker: string; angle: string; text: string }
type DailyBattle = {
  id: string
  date: string
  topic: string
  angle_a: string
  angle_b: string
  messages: DailyBattleMsg[]
  winner: string | null
  reason: string | null
  votes_a: number
  votes_b: number
}

export default function Home() {
  const [topic, setTopic] = useState('')
  const [angle, setAngle] = useState('Hot Take')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<{ headline: string; body: string } | null>(null)
  const [user, setUser] = useState<User | null>(null)
  const [shared, setShared] = useState(false)
  const [takesCount, setTakesCount] = useState<number | null>(null)
  const [featuredTakes, setFeaturedTakes] = useState<Take[]>([])
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Daily battle state
  const [battle, setBattle] = useState<DailyBattle | null>(null)
  const [battleLoading, setBattleLoading] = useState(true)
  const [votedSide, setVotedSide] = useState<string | null>(null)
  const [voting, setVoting] = useState(false)

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => setUser(data.user))
    supabase.auth.onAuthStateChange((_e, session) => setUser(session?.user ?? null))
    fetchStats()
    fetchDailyBattle()
  }, [])

  const fetchDailyBattle = async () => {
    try {
      const res = await fetch('/api/daily-battle')
      if (!res.ok) { setBattleLoading(false); return }
      const data = await res.json()
      if (data?.id) {
        setBattle(data)
        const stored = localStorage.getItem(`dbvote_${data.date}`)
        if (stored) setVotedSide(stored)
      }
    } catch (e) {
      console.error(e)
    } finally {
      setBattleLoading(false)
    }
  }

  const voteBattle = async (side: 'A' | 'B') => {
    if (!battle || votedSide || voting) return
    setVoting(true)
    try {
      const res = await fetch('/api/daily-battle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: battle.id, side }),
      })
      const data = await res.json()
      if (res.ok) {
        setBattle({ ...battle, votes_a: data.votes_a, votes_b: data.votes_b })
        setVotedSide(side)
        localStorage.setItem(`dbvote_${battle.date}`, side)
      }
    } catch (e) {
      console.error(e)
    } finally {
      setVoting(false)
    }
  }

  const fetchStats = async () => {
    try {
      const { count } = await supabase
        .from('takes')
        .select('*', { count: 'exact', head: true })
      setTakesCount(count ?? 0)

      const { data } = await supabase
        .from('takes')
        .select('id, topic, angle, headline, body, upvotes')
        .order('upvotes', { ascending: false })
        .limit(3)
      setFeaturedTakes(data || [])
    } catch {
      setTakesCount(0)
    }
  }

  const generate = async (topicOverride?: string) => {
    const t = topicOverride || topic
    if (!t.trim()) return
    if (topicOverride) setTopic(topicOverride)
    setLoading(true)
    setResult(null)
    setShared(false)
    setError(null)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t, angle, userId: user?.id }),
      })
      const data = await res.json()
      if (!res.ok || data.error) {
        setError(data.error || 'Something went wrong. Please try again.')
        return
      }
      setResult(data)
      if (user?.id) {
        setShared(true)
        setTakesCount(prev => prev !== null ? prev + 1 : prev)
      }
    } catch (e) {
      console.error(e)
      setError('Connection error. Please check your internet and try again.')
    } finally {
      setLoading(false)
    }
  }

  const shareText = result
    ? `${result.headline}\n\n${result.body.slice(0, 200)}...\n\nGet AI takes on anything at thoughtofview.com`
    : ''

  const formatCount = (n: number) => n >= 1000 ? `${(n / 1000).toFixed(1)}k` : n.toString()

  const totalVotes = battle ? (battle.votes_a || 0) + (battle.votes_b || 0) : 0
  const pctA = totalVotes > 0 && battle ? Math.round((battle.votes_a / totalVotes) * 100) : 50
  const pctB = 100 - pctA

  return (
    <div className="min-h-screen bg-[#F0EDE6]">
      <Script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9438165116015593"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />

      {/* Announcement bar */}
      <div className="bg-[#1A1A1A] text-[#F0EDE6] text-xs text-center py-2 px-4 tracking-wide">
        ⚔️ A new AI battle every day. Vote for the winner — then see if the judge agrees.
      </div>

      {/* ============ DAILY BATTLE HERO ============ */}
      <div className="relative overflow-hidden" style={{ background: '#0a0d12' }}>
        <div style={{ position: 'absolute', inset: 0, backgroundImage: "url('/arena-bg.png')", backgroundSize: 'cover', backgroundPosition: 'center', opacity: 0.5 }} />
        <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(10,13,18,0.55) 0%, rgba(10,13,18,0.75) 60%, rgba(10,13,18,0.95) 100%)' }} />

        <div className="relative max-w-4xl mx-auto px-4 pt-12 pb-14">
          <p className="text-xs font-sans uppercase tracking-widest text-[#4dd9c0] mb-3 text-center">
            ⚔️ Today's Battle · {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}
          </p>
          <h1 className="font-serif text-4xl md:text-6xl font-bold leading-tight mb-2 text-white text-center">
            Two AIs. One topic.<br />You pick the winner.
          </h1>
          <p className="text-base text-[#8b949e] text-center mb-8">
            Got a thought? Get a view.
          </p>

          {battleLoading && (
            <div className="bg-[#0d1117]/90 border border-[#21262d] rounded-2xl p-10 text-center">
              <p className="text-[#4dd9c0] font-semibold text-sm">⚔️ Loading today's battle...</p>
            </div>
          )}

          {!battleLoading && !battle && (
            <div className="bg-[#0d1117]/90 border border-[#21262d] rounded-2xl p-10 text-center">
              <p className="text-[#8b949e] text-sm mb-4">Today's battle is warming up. Try your own matchup:</p>
              <Link href="/battle" className="inline-block bg-[#e85d3a] text-white font-bold px-8 py-3 rounded-xl text-sm uppercase tracking-wider">
                ⚔️ Start a Battle
              </Link>
            </div>
          )}

          {battle && (
            <div className="bg-[#0d1117]/95 border border-[#21262d] rounded-2xl overflow-hidden shadow-2xl">
              {/* Matchup header */}
              <div className="flex items-center justify-center gap-4 px-6 py-4 border-b border-[#21262d]" style={{ background: 'linear-gradient(90deg, rgba(232,93,58,0.1), transparent 50%, rgba(124,58,237,0.1))' }}>
                <span className="font-bold text-sm" style={{ color: ANGLE_COLORS[battle.angle_a] || '#e85d3a' }}>
                  {ANGLE_ICONS[battle.angle_a]} {battle.angle_a}
                </span>
                <span className="text-[#555] font-black">⚔️</span>
                <span className="font-bold text-sm" style={{ color: ANGLE_COLORS[battle.angle_b] || '#7c3aed' }}>
                  {ANGLE_ICONS[battle.angle_b]} {battle.angle_b}
                </span>
              </div>
              <p className="text-center text-[#4dd9c0] text-sm font-semibold uppercase tracking-wider pt-4">"{battle.topic}"</p>

              {/* Transcript */}
              <div className="px-4 md:px-8 py-5 max-h-96 overflow-y-auto">
                {(battle.messages || []).map((m, i) => {
                  const isA = m.speaker === 'A'
                  const color = ANGLE_COLORS[m.angle] || (isA ? '#e85d3a' : '#7c3aed')
                  return (
                    <div key={i} className={`flex ${isA ? 'justify-start' : 'justify-end'} mb-3`}>
                      <div style={{ maxWidth: '80%', background: `${color}18`, border: `1px solid ${color}44`, borderRadius: isA ? '12px 12px 12px 4px' : '12px 12px 4px 12px', padding: '10px 14px' }}>
                        <p style={{ color, fontSize: 10, fontWeight: 700, marginBottom: 4, textTransform: 'uppercase' }}>{ANGLE_ICONS[m.angle]} {m.angle}</p>
                        <p className="text-[#e2e8f0] text-sm leading-relaxed">{m.text}</p>
                      </div>
                    </div>
                  )
                })}
              </div>

              {/* Voting */}
              <div className="px-4 md:px-8 pb-6">
                {!votedSide ? (
                  <div>
                    <p className="text-center text-white font-serif font-bold text-lg mb-4">Who won?</p>
                    <div className="grid grid-cols-2 gap-3">
                      <button onClick={() => voteBattle('A')} disabled={voting}
                        className="py-3.5 rounded-xl font-bold text-sm text-white transition-transform hover:scale-[1.02]"
                        style={{ background: ANGLE_COLORS[battle.angle_a] || '#e85d3a' }}>
                        {ANGLE_ICONS[battle.angle_a]} {battle.angle_a}
                      </button>
                      <button onClick={() => voteBattle('B')} disabled={voting}
                        className="py-3.5 rounded-xl font-bold text-sm text-white transition-transform hover:scale-[1.02]"
                        style={{ background: ANGLE_COLORS[battle.angle_b] || '#7c3aed' }}>
                        {ANGLE_ICONS[battle.angle_b]} {battle.angle_b}
                      </button>
                    </div>
                    <p className="text-center text-[#556] text-xs mt-3">Vote to reveal the community results and the AI judge's verdict</p>
                  </div>
                ) : (
                  <div>
                    {/* Community results bar */}
                    <p className="text-center text-[#8b949e] text-xs uppercase tracking-wider font-bold mb-3">
                      Community vote · {totalVotes} vote{totalVotes === 1 ? '' : 's'}
                    </p>
                    <div className="flex h-9 rounded-xl overflow-hidden mb-2 border border-[#21262d]">
                      <div className="flex items-center justify-start pl-3 text-white text-xs font-bold transition-all duration-700"
                        style={{ width: `${Math.max(pctA, 12)}%`, background: ANGLE_COLORS[battle.angle_a] || '#e85d3a' }}>
                        {pctA}%
                      </div>
                      <div className="flex items-center justify-end pr-3 text-white text-xs font-bold transition-all duration-700"
                        style={{ width: `${Math.max(pctB, 12)}%`, background: ANGLE_COLORS[battle.angle_b] || '#7c3aed' }}>
                        {pctB}%
                      </div>
                    </div>
                    <p className="text-center text-[#556] text-xs mb-4">
                      You voted {votedSide === 'A' ? battle.angle_a : battle.angle_b}
                    </p>

                    {/* AI judge verdict */}
                    {battle.winner && (
                      <div className="rounded-xl p-4 text-center" style={{ background: 'rgba(77,217,192,0.08)', border: '1px solid rgba(77,217,192,0.3)' }}>
                        <p className="text-[#4dd9c0] text-xs font-bold uppercase tracking-widest mb-1">🏆 AI Judge Verdict</p>
                        <p className="text-white font-serif font-bold text-xl">{battle.winner}</p>
                        {battle.reason && <p className="text-[#8b949e] text-sm italic mt-1">"{battle.reason}"</p>}
                        <p className="text-[#556] text-xs mt-3">
                          {((votedSide === 'A' && battle.winner === battle.angle_a) || (votedSide === 'B' && battle.winner === battle.angle_b))
                            ? '✓ You agreed with the judge'
                            : '✗ You and the judge disagree — maybe you\'re right'}
                        </p>
                      </div>
                    )}

                    <div className="flex justify-center gap-3 mt-4">
                      <Link href="/battle" className="text-xs font-bold text-[#e85d3a] hover:underline uppercase tracking-wider">
                        ⚔️ Make your own battle →
                      </Link>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          <p className="text-center text-[#556] text-xs mt-5">New battle every day at midnight · Come back tomorrow</p>
        </div>
      </div>

      {/* ============ NEWSLETTER STRIP ============ */}
      <div className="bg-[#1c1a16] border-y border-black/20">
        <div className="max-w-4xl mx-auto px-4 py-6 flex flex-col sm:flex-row items-center gap-4">
          <div className="flex-1 text-center sm:text-left">
            <p className="font-serif text-lg font-bold text-[#f0ede6]">Tomorrow's battle, in your inbox</p>
            <p className="text-xs text-[#b0ac9f]">Plus 3 sharp AI takes on the day's biggest topics. Free, no spam.</p>
          </div>
          <form className="flex gap-2 w-full sm:w-auto" action="https://dc090f69.sibforms.com/serve/MUIFAJgWdUk-T8_WFwc7NtbcuIW5Y3wZKv7LUr6qcOf5S2yCVf4IbBcGOUEPjtQqPW32qkJLcwQK_wjuYTRAaYAcAbXt8pCjZNS20EgCyx4vrWSuRxrGl-7nARl48iWf3WfikOKMA4k3qeRJ_oCNCDobsawb9tGQE-EKz5mHsOsKbPxAOCEAuin9I_KvKXekjGlOPH1iFFx4n1qhYg==" method="POST">
            <input type="email" name="EMAIL" placeholder="your@email.com" required
              className="flex-1 sm:w-56 px-3 py-2.5 text-sm rounded-lg bg-[#2a2824] text-[#f0ede6] border border-[#444] outline-none focus:border-brand-orange" />
            <button type="submit"
              className="px-5 py-2.5 text-sm font-bold uppercase tracking-wider bg-yellow-400 text-[#1a1500] rounded-lg hover:bg-yellow-300 transition-colors whitespace-nowrap">
              Subscribe
            </button>
            <input type="hidden" name="locale" value="en" />
            <input type="hidden" name="html_type" value="simple" />
          </form>
        </div>
      </div>

      {/* ============ GENERATOR ============ */}
      <div className="max-w-4xl mx-auto px-4 pt-14 pb-4">
        <h2 className="font-serif text-3xl md:text-4xl font-bold leading-tight mb-2 text-center">
          Or get a take on anything.
        </h2>
        <p className="text-brand-muted text-center mb-8">
          Five angles. Any topic. Under 5 seconds.
        </p>
      </div>

      <div className="max-w-4xl mx-auto px-4 pb-14">
        <div className="bg-[#1A1A1A] rounded-2xl p-6 md:p-8">
          <p className="text-xs font-sans uppercase tracking-widest text-[#888] mb-3">Enter a topic, question, or debate</p>
          <div className="flex flex-col sm:flex-row gap-3 mb-6">
            <input
              value={topic}
              onChange={e => setTopic(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && generate()}
              placeholder="e.g. remote work, AI, crypto, democracy..."
              className="flex-1 bg-[#2A2A2A] text-white rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-brand-orange placeholder:text-[#555]"
            />
            <button
              onClick={() => generate()}
              disabled={loading || !topic.trim()}
              className="bg-brand-orange text-white font-semibold px-6 py-3 rounded-xl hover:bg-orange-700 transition-colors disabled:opacity-50 w-full sm:w-auto"
            >
              {loading ? 'Thinking...' : 'Get the Take →'}
            </button>
          </div>
          <p className="text-xs font-sans uppercase tracking-widest text-[#888] mb-3">Choose your angle</p>
          <div className="flex flex-wrap gap-2 mb-4">
            {ANGLES.map(a => (
              <button key={a} onClick={() => setAngle(a)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${angle === a ? 'bg-brand-orange text-white' : 'bg-[#2A2A2A] text-[#ccc] hover:bg-[#333]'}`}>
                {ANGLE_ICONS[a]} {a}
              </button>
            ))}
          </div>

          <div className="flex flex-wrap gap-2 mb-6">
            {TRENDING_TOPICS.map(t => (
              <button key={t} onClick={() => generate(t)}
                className="px-3 py-1.5 text-xs font-medium border border-[#333] rounded-full text-[#888] hover:text-white hover:border-[#666] transition-colors">
                {t}
              </button>
            ))}
          </div>

          {error && !loading && (
            <div className="border-l-2 border-yellow-500 pl-4 py-2">
              <p className="text-yellow-400 text-sm font-medium">⚠️ {error}</p>
              {error.includes('overwhelmed') && (
                <p className="text-[#888] text-xs mt-1">Rate limit hit — wait 30 seconds and try again.</p>
              )}
              {error.includes('limit reached') && (
                <a href="/premium" className="text-brand-orange text-xs underline mt-1 block">Upgrade to Premium for unlimited takes →</a>
              )}
            </div>
          )}

          {loading && (
            <div className="border-l-2 border-brand-orange pl-4 py-2">
              <div className="h-4 bg-[#2A2A2A] rounded animate-pulse mb-3 w-2/3" />
              <div className="h-3 bg-[#2A2A2A] rounded animate-pulse mb-2" />
              <div className="h-3 bg-[#2A2A2A] rounded animate-pulse mb-2 w-4/5" />
            </div>
          )}

          {result && !loading && (
            <div className="border-l-2 border-brand-orange pl-4">
              <div className="flex gap-2 mb-3">
                <span className="text-xs bg-[#2A2A2A] text-[#888] px-3 py-1 rounded-full uppercase tracking-wider">{topic}</span>
                <span className="text-xs bg-brand-orange text-white px-3 py-1 rounded-full uppercase tracking-wider">{angle}</span>
              </div>
              <h2 className="text-white font-serif text-2xl font-bold mb-3">{result.headline}</h2>
              <div className="text-[#ccc] text-sm leading-relaxed whitespace-pre-wrap mb-4">{result.body}</div>
              {shared && <p className="text-xs text-brand-orange mb-3">✓ Saved to public feed</p>}
              <div className="flex gap-2 flex-wrap">
                <a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`} target="_blank" rel="noopener noreferrer"
                  className="text-xs border border-[#444] text-[#ccc] px-4 py-2 rounded-full hover:border-[#888] transition-colors">
                  Share on X
                </a>
                <button onClick={() => navigator.clipboard.writeText(shareText)}
                  className="text-xs border border-[#444] text-[#ccc] px-4 py-2 rounded-full hover:border-[#888] transition-colors">
                  Copy
                </button>
                <Link href="/cards"
                  className="text-xs border border-[#4dd9c0] text-[#4dd9c0] px-4 py-2 rounded-full hover:bg-[#4dd9c0] hover:text-black transition-colors">
                  🎨 Make it a card
                </Link>
                {!user && (
                  <button onClick={() => supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } })}
                    className="text-xs border border-brand-orange text-brand-orange px-4 py-2 rounded-full hover:bg-brand-orange hover:text-white transition-colors">
                    Sign in to save & share →
                  </button>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ============ SOCIAL PROOF ============ */}
      <div className="max-w-4xl mx-auto px-4 pb-14">
        <div className="bg-[#0d1117] rounded-2xl px-6 py-5 flex flex-wrap items-center justify-center gap-6 md:gap-12">
          <div className="text-center">
            <div className="text-2xl font-bold text-white">{takesCount !== null && takesCount > 0 ? formatCount(takesCount) : '5'}</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">{takesCount !== null && takesCount > 0 ? 'Takes Generated' : 'AI Angles'}</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">Daily</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">New Battles</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">Free</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">To Get Started</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">{"< 5s"}</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">Per Take</div>
          </div>
        </div>
      </div>

      {/* ============ TOP TAKES (community proof) ============ */}
      {featuredTakes.length > 0 && (
        <div className="max-w-4xl mx-auto px-4 pb-14">
          <div className="flex items-center justify-between border-b-2 border-black pb-2 mb-4">
            <h2 className="font-serif text-2xl font-bold">Top Takes from the Feed</h2>
            <Link href="/feed" className="text-xs font-bold text-brand-orange hover:underline uppercase tracking-wider">
              View all →
            </Link>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {featuredTakes.map(take => (
              <Link key={take.id} href="/feed" className="bg-white border border-gray-200 rounded-xl p-5 hover:border-[#4dd9c0]/40 transition-colors block">
                <div className="flex gap-2 mb-3 flex-wrap">
                  <span className="text-xs text-white px-2.5 py-0.5 rounded-full uppercase tracking-wider font-medium" style={{ background: ANGLE_COLORS[take.angle] || '#666' }}>
                    {ANGLE_ICONS[take.angle]} {take.angle}
                  </span>
                </div>
                <h3 className="font-serif font-bold text-base mb-2 leading-snug line-clamp-2">{take.headline}</h3>
                <p className="text-xs text-gray-500 line-clamp-2 mb-3">{take.body}</p>
                <span className="text-xs text-gray-400">▲ {take.upvotes || 0} upvotes</span>
              </Link>
            ))}
          </div>
        </div>
      )}

      {/* ============ FEATURE ROW ============ */}
      <div className="max-w-4xl mx-auto px-4 pb-14">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Battle */}
          <Link href="/battle" className="rounded-2xl overflow-hidden border border-[#1a2a3a] relative group block">
            <div style={{ position: 'absolute', inset: 0, backgroundImage: "url('/arena-bg.png')", backgroundSize: 'cover', backgroundPosition: 'center', opacity: 0.4 }} />
            <div style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.65)' }} />
            <div className="relative z-10 p-6">
              <div className="text-2xl mb-2">⚔️</div>
              <h3 className="font-serif font-bold text-lg text-white mb-1">Take Battle</h3>
              <p className="text-xs text-[#aaa] leading-relaxed mb-3">Pick two angles and any topic. Watch them fight. AI judge picks the winner.</p>
              <span className="text-xs font-bold text-[#e85d3a] uppercase tracking-wider group-hover:underline">Start a battle →</span>
            </div>
          </Link>
          {/* Cards */}
          <Link href="/cards" className="bg-[#0d1117] rounded-2xl border border-[#1a2a3a] p-6 group block">
            <div className="text-2xl mb-2">🎨</div>
            <h3 className="font-serif font-bold text-lg text-white mb-1">Take Cards</h3>
            <p className="text-xs text-[#8b949e] leading-relaxed mb-3">Turn any take into a shareable 1080×1080 photo card for Instagram and X.</p>
            <span className="text-xs font-bold text-[#4dd9c0] uppercase tracking-wider group-hover:underline">Create a card →</span>
          </Link>
          {/* OpinionBot */}
          <Link href="/opinionbot" className="bg-[#1A1A1A] rounded-2xl border border-[#2a2a2a] p-6 group block">
            <div className="text-2xl mb-2">🤖</div>
            <h3 className="font-serif font-bold text-lg text-white mb-1">OpinionBot</h3>
            <p className="text-xs text-[#888] leading-relaxed mb-3">The desktop app. AI takes from your taskbar — Windows & Mac, one-time purchase.</p>
            <span className="text-xs font-bold text-brand-orange uppercase tracking-wider group-hover:underline">Get the app →</span>
          </Link>
        </div>
      </div>

      {/* ============ PREMIUM STRIP ============ */}
      <div className="max-w-4xl mx-auto px-4 pb-14">
        <div className="bg-[#0d1117] rounded-2xl border border-[#1a2a3a] p-6 md:p-8 flex flex-col md:flex-row items-center gap-6">
          <div className="flex-1 text-center md:text-left">
            <p className="text-xs font-bold uppercase tracking-widest text-[#e85d3a] mb-2">⚡ Premium</p>
            <h3 className="font-serif text-2xl font-bold text-white mb-1">Unlimited takes. No ads. Priority speed.</h3>
            <p className="text-sm text-[#8b949e]">Everything Thought of View has to offer, for less than a coffee a month.</p>
          </div>
          <Link href="/premium"
            className="bg-[#e85d3a] text-white font-bold px-8 py-3.5 rounded-xl hover:bg-orange-700 transition-colors text-sm uppercase tracking-wider whitespace-nowrap">
            Upgrade — $5/mo
          </Link>
        </div>
      </div>

      {/* ============ FAQ ============ */}
      <div className="max-w-4xl mx-auto px-4 pb-16">
        <div className="flex items-center justify-between border-b-2 border-black pb-2 mb-4">
          <h2 className="font-serif text-2xl font-bold">Common Questions</h2>
          <Link href="/faq" className="text-xs font-bold text-brand-orange hover:underline uppercase tracking-wider">
            Full FAQ →
          </Link>
        </div>
        <div className="space-y-2">
          {HOME_FAQS.map((faq, i) => (
            <div key={i} className="bg-white rounded-xl border border-gray-200 overflow-hidden">
              <button
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full flex items-center justify-between px-5 py-4 text-left font-medium text-sm hover:bg-gray-50 transition-colors"
              >
                <span>{faq.q}</span>
                <span className="text-gray-400 ml-4 shrink-0">{openFaq === i ? '▲' : '▼'}</span>
              </button>
              {openFaq === i && (
                <div className="px-5 pb-4 text-sm text-gray-600 leading-relaxed border-t border-gray-100 pt-3">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* ============ FOOTER ============ */}
      <footer className="border-t border-gray-300 bg-[#F0EDE6] py-8 px-4 text-center">
        <a href="/" className="font-serif text-2xl font-bold mb-4 inline-block">Thought<span className="text-brand-orange">of</span>View</a>
        <div className="flex justify-center gap-6 text-xs text-gray-500 mb-4 flex-wrap">
          <a href="/about" className="hover:text-black">About</a>
          <a href="/faq" className="hover:text-black">FAQ</a>
          <a href="/battle" className="hover:text-black">Battle</a>
          <a href="/cards" className="hover:text-black">Cards</a>
          <a href="/privacy" className="hover:text-black">Privacy Policy</a>
          <a href="/terms" className="hover:text-black">Terms of Use</a>
          <a href="/contact" className="hover:text-black">Contact</a>
          <a href="/advertise" className="hover:text-black">Advertise</a>
        </div>
        <p className="text-xs text-gray-400">
          © 2026 ThoughtofView.com · AI-generated content for entertainment and informational purposes.<br />
          This site contains affiliate links and advertising. <a href="/disclosure" className="underline">Disclosure</a>.
        </p>
      </footer>

      <div id="cookie-banner" className="fixed bottom-0 left-0 right-0 bg-[#1A1A1A] text-white text-sm px-4 py-3 flex items-center justify-between gap-4 z-50">
        <p>We use cookies for ads and analytics. <a href="/privacy" className="underline text-yellow-400">Learn more</a>.</p>
        <button onClick={() => { document.getElementById('cookie-banner')!.style.display='none'; localStorage.setItem('cookies_ok','1') }}
          className="bg-brand-orange text-white text-xs font-bold px-4 py-2 rounded-full whitespace-nowrap">
          Accept & Continue
        </button>
      </div>
    </div>
  )
}
