'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import Script from 'next/script'
import Link from 'next/link'
import type { User } from '@supabase/supabase-js'

const ANGLES = ['Hot Take', 'Balanced', "Devil's Advocate", 'Contrarian', 'Expert Analysis']
const ANGLE_ICONS: Record<string, string> = {
  'Hot Take': '🔥',
  'Balanced': '⚖️',
  "Devil's Advocate": '😈',
  'Contrarian': '↩️',
  'Expert Analysis': '🎓',
}
const ANGLE_COLORS: Record<string, string> = {
  'Hot Take': 'bg-[#e85d3a]',
  'Balanced': 'bg-[#3a7bd5]',
  "Devil's Advocate": 'bg-[#7c3aed]',
  'Contrarian': 'bg-[#d97706]',
  'Expert Analysis': 'bg-[#059669]',
}

const TRENDING_TOPICS = [
  'AI & Jobs', 'Bitcoin', 'Remote Work', 'Social Media', 'UBI',
  'College Degrees', 'Cancel Culture', 'Climate Change', '4-Day Week', 'Crypto'
]

const BOOKS = [
  { tag: 'Critical Thinking', title: 'Thinking, Fast and Slow', desc: "Kahneman's masterwork on how we form opinions and where we go wrong.", link: 'https://www.amazon.com/dp/0374533555?tag=drmetal1776-20' },
  { tag: 'Arguing Better', title: 'Thank You for Arguing', desc: 'The definitive guide to rhetoric, persuasion, and winning any debate.', link: 'https://www.amazon.com/dp/0307455998?tag=drmetal1776-20' },
  { tag: 'Big Ideas', title: 'The Scout Mindset', desc: 'Why seeking truth over being right leads to better thinking and decisions.', link: 'https://www.amazon.com/dp/0735217556?tag=drmetal1776-20' },
  { tag: 'Contrarian Lens', title: 'Zero to One', desc: "Thiel's contrarian manifesto on building the future by thinking differently.", link: 'https://www.amazon.com/dp/0804139296?tag=drmetal1776-20' },
]

const TOOLS = [
  { tag: 'Research', title: 'Audible', desc: 'Listen to the books above and thousands more. First month free.', link: 'https://www.audible.com', cta: 'Try Free →' },
  { tag: 'Note-Taking', title: 'Notion', desc: 'Capture and organise your best takes, arguments, and research.', link: 'https://www.notion.so', cta: 'Get Notion →' },
]

const HOME_FAQS = [
  { q: 'Is Thought of View free?', a: 'Yes — free accounts get 5 takes per day across all angles. Premium members ($5/month) get unlimited takes, no ads, and priority generation.' },
  { q: 'Do I need an account?', a: 'No account needed to generate takes. Sign in with Google to save takes to the public feed, upvote, and comment.' },
  { q: 'How are the takes generated?', a: 'Takes are generated by AI language models via the Groq API. Each angle is prompted differently to produce a distinct, argued perspective on your topic.' },
  { q: 'What is OpinionBot?', a: 'OpinionBot is a native desktop app ($4.99 one-time) for Windows and Mac. It lets you generate AI takes from your taskbar without opening a browser.' },
  { q: 'Can I trust the takes?', a: 'Takes are sharp opinions, not factual summaries. They\'re great for debate prep, understanding different viewpoints, and exploring arguments. Always verify facts independently.' },
]

const AUTO_TOPICS = [
  { topic: 'AI replacing creative jobs', angle: 'Hot Take' },
  { topic: 'Remote work', angle: 'Contrarian' },
  { topic: 'Social media and mental health', angle: "Devil's Advocate" },
  { topic: 'Bitcoin as a currency', angle: 'Expert Analysis' },
  { topic: 'College degrees', angle: 'Hot Take' },
  { topic: 'The 4-day work week', angle: 'Balanced' },
  { topic: 'Big Tech monopolies', angle: 'Contrarian' },
  { topic: 'Universal Basic Income', angle: 'Expert Analysis' },
]

const CARD_EXAMPLES = [
  {
    angle: 'Hot Take',
    angleColor: '#e85d3a',
    angleEmoji: '🔥',
    topic: 'Remote Work',
    headline: 'Remote Work Didn\'t Kill Productivity — It Killed the Illusion',
    body: 'Companies demanding RTO aren\'t protecting culture. They\'re protecting middle management jobs that only exist to supervise people.',
    photo: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=60',
  },
  {
    angle: 'Contrarian',
    angleColor: '#d97706',
    angleEmoji: '↩️',
    topic: 'Bitcoin',
    headline: 'Bitcoin Is the Most Successful Marketing Campaign in Financial History',
    body: 'It has no cash flows, no intrinsic value. Its "store of value" thesis requires everyone to keep believing in it. That\'s not a currency. That\'s a religion.',
    photo: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&q=60',
  },
  {
    angle: "Devil's Advocate",
    angleColor: '#7c3aed',
    angleEmoji: '😈',
    topic: 'AI & Jobs',
    headline: 'Maybe AI Should Replace Most Jobs',
    body: 'We built a society where humans must work to deserve to live. AI could free us from that. The question isn\'t "will AI take jobs" — it\'s "why are we so attached to having them?"',
    photo: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=60',
  },
  {
    angle: 'Expert Analysis',
    angleColor: '#059669',
    angleEmoji: '🎓',
    topic: 'College Degrees',
    headline: 'The ROI on a Four-Year Degree Has Fundamentally Broken',
    body: 'The credential is no longer the signal. Employers know it. Students are figuring it out. The question is whether universities will adapt before the market does it for them.',
    photo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400&q=60',
  },
]

type Take = {
  id: string
  topic: string
  angle: string
  headline: string
  body: string
  upvotes: number
}

export default function Home() {
  const [topic, setTopic] = useState('')
  const [angle, setAngle] = useState('Hot Take')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<{ headline: string; body: string } | null>(null)
  const [user, setUser] = useState<User | null>(null)
  const [shared, setShared] = useState(false)
  const [takesCount, setTakesCount] = useState<number | null>(null)
  const [featuredTakes, setFeaturedTakes] = useState<Take[]>([])
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [isAutoGenerated, setIsAutoGenerated] = useState(false)
  const [cardIndex, setCardIndex] = useState(0)

  useEffect(() => {
    const timer = setInterval(() => {
      setCardIndex(i => (i + 1) % CARD_EXAMPLES.length)
    }, 3000)
    return () => clearInterval(timer)
  }, [])

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => setUser(data.user))
    supabase.auth.onAuthStateChange((_e, session) => setUser(session?.user ?? null))
    fetchStats()
    autoGenerate()
  }, [])

  const autoGenerate = async () => {
    const pick = AUTO_TOPICS[Math.floor(Math.random() * AUTO_TOPICS.length)]
    setTopic(pick.topic)
    setAngle(pick.angle)
    setLoading(true)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: pick.topic, angle: pick.angle }),
      })
      const data = await res.json()
      if (res.ok && !data.error) {
        setResult(data)
        setIsAutoGenerated(true)
      }
    } catch (e) {
      console.error('Auto-generate failed:', e)
    } finally {
      setLoading(false)
    }
  }

  const fetchStats = async () => {
    const { count } = await supabase
      .from('takes')
      .select('*', { count: 'exact', head: true })
    setTakesCount(count || 0)

    const { data } = await supabase
      .from('takes')
      .select('id, topic, angle, headline, body, upvotes')
      .order('upvotes', { ascending: false })
      .limit(3)
    setFeaturedTakes(data || [])
  }

  const generate = async (topicOverride?: string) => {
    const t = topicOverride || topic
    if (!t.trim()) return
    if (topicOverride) setTopic(topicOverride)
    setLoading(true)
    setResult(null)
    setShared(false)
    setError(null)
    setIsAutoGenerated(false)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t, angle, userId: user?.id }),
      })
      const data = await res.json()
      if (!res.ok || data.error) {
        setError(data.error || 'Something went wrong. Please try again.')
        return
      }
      setResult(data)
      if (user?.id) {
        setShared(true)
        setTakesCount(prev => prev !== null ? prev + 1 : prev)
      }
    } catch (e) {
      console.error(e)
      setError('Connection error. Please check your internet and try again.')
    } finally {
      setLoading(false)
    }
  }

  const shareText = result
    ? `${result.headline}\n\n${result.body.slice(0, 200)}...\n\nGet AI takes on anything at thoughtofview.com`
    : ''

  const formatCount = (n: number) => {
    if (n >= 1000) return `${(n / 1000).toFixed(1)}k`
    return n.toString()
  }

  return (
    <div className="min-h-screen bg-[#F0EDE6]">
      <Script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9438165116015593"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />

      <div className="bg-[#1A1A1A] text-[#F0EDE6] text-xs text-center py-2 px-4 tracking-wide">
        🔥 Get Hot Takes, Contrarian Views, or Devil's Advocate perspectives on any topic — instantly.
      </div>

      <div className="max-w-6xl mx-auto px-4 pt-10 pb-4">
        <p className="text-xs font-sans uppercase tracking-widest text-brand-muted mb-4">AI Opinion Engine</p>
        <h1 className="font-serif text-5xl md:text-7xl font-bold leading-tight mb-3 max-w-3xl">
          Stop guessing. Start arguing.
        </h1>
        <p className="font-serif text-2xl md:text-3xl text-brand-muted italic mb-4">Got a thought? Get a view.</p>
        <p className="text-lg text-brand-muted max-w-xl mb-8">
          AI-powered perspectives on politics, tech, finance, culture. Five angles. Zero fluff.
        </p>
      </div>

      <div className="max-w-6xl mx-auto px-4 pb-10">
        <div className="bg-[#1A1A1A] rounded-2xl p-6 md:p-8">
          <p className="text-xs font-sans uppercase tracking-widest text-[#888] mb-3">Enter a topic, question, or debate</p>
          <div className="flex flex-col sm:flex-row gap-3 mb-6">
            <input
              value={topic}
              onChange={e => setTopic(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && generate()}
              placeholder="e.g. remote work, AI, crypto, democracy..."
              className="flex-1 bg-[#2A2A2A] text-white rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-brand-orange placeholder:text-[#555]"
            />
            <button
              onClick={() => generate()}
              disabled={loading || !topic.trim()}
              className="bg-brand-orange text-white font-semibold px-6 py-3 rounded-xl hover:bg-orange-700 transition-colors disabled:opacity-50 w-full sm:w-auto"
            >
              {loading ? 'Thinking...' : 'Get the Take →'}
            </button>
          </div>
          <p className="text-xs font-sans uppercase tracking-widest text-[#888] mb-3">Choose your angle</p>
          <div className="flex flex-wrap gap-2 mb-6">
            {ANGLES.map(a => (
              <button key={a} onClick={() => setAngle(a)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${angle === a ? 'bg-brand-orange text-white' : 'bg-[#2A2A2A] text-[#ccc] hover:bg-[#333]'}`}>
                {ANGLE_ICONS[a]} {a}
              </button>
            ))}
          </div>

          {error && !loading && (
            <div className="border-l-2 border-yellow-500 pl-4 py-2">
              <p className="text-yellow-400 text-sm font-medium">⚠️ {error}</p>
              {error.includes('overwhelmed') && (
                <p className="text-[#888] text-xs mt-1">Groq rate limit hit — wait 30 seconds and try again.</p>
              )}
              {error.includes('limit reached') && (
                <a href="/premium" className="text-brand-orange text-xs underline mt-1 block">Upgrade to Premium for unlimited takes →</a>
              )}
            </div>
          )}

          {loading && (            <div className="border-l-2 border-brand-orange pl-4 py-2">
              <div className="h-4 bg-[#2A2A2A] rounded animate-pulse mb-3 w-2/3" />
              <div className="h-3 bg-[#2A2A2A] rounded animate-pulse mb-2" />
              <div className="h-3 bg-[#2A2A2A] rounded animate-pulse mb-2 w-4/5" />
            </div>
          )}

          {result && !loading && (
            <div className="border-l-2 border-brand-orange pl-4">
              {isAutoGenerated && (
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs text-[#4dd9c0] uppercase tracking-wider font-medium">✦ Example take — try your own topic above</span>
                  <button
                    onClick={autoGenerate}
                    className="text-xs text-[#888] hover:text-white transition-colors"
                  >
                    Try another →
                  </button>
                </div>
              )}
              <div className="flex gap-2 mb-3">
                <span className="text-xs bg-[#2A2A2A] text-[#888] px-3 py-1 rounded-full uppercase tracking-wider">{topic}</span>
                <span className="text-xs bg-brand-orange text-white px-3 py-1 rounded-full uppercase tracking-wider">{angle}</span>
              </div>
              <h2 className="text-white font-serif text-2xl font-bold mb-3">{result.headline}</h2>
              <div className="text-[#ccc] text-sm leading-relaxed whitespace-pre-wrap mb-4">{result.body}</div>
              {shared && <p className="text-xs text-brand-orange mb-3">✓ Saved to public feed</p>}
              <div className="flex gap-2 flex-wrap">
                <a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`} target="_blank" rel="noopener noreferrer"
                  className="text-xs border border-[#444] text-[#ccc] px-4 py-2 rounded-full hover:border-[#888] transition-colors">
                  Share on X
                </a>
                <button onClick={() => navigator.clipboard.writeText(shareText)}
                  className="text-xs border border-[#444] text-[#ccc] px-4 py-2 rounded-full hover:border-[#888] transition-colors">
                  Copy
                </button>
                {!user && (
                  <button onClick={() => supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } })}
                    className="text-xs border border-brand-orange text-brand-orange px-4 py-2 rounded-full hover:bg-brand-orange hover:text-white transition-colors">
                    Sign in to save & share →
                  </button>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Social Proof Bar */}
      <div className="max-w-6xl mx-auto px-4 pb-10">
        <div className="bg-[#0d1117] rounded-2xl px-6 py-5 flex flex-wrap items-center justify-center gap-6 md:gap-12">
          <div className="text-center">
            <div className="text-2xl font-bold text-white">
              {takesCount !== null ? formatCount(takesCount) : '—'}
            </div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">Takes Generated</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">5</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">AI Angles</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">Free</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">To Get Started</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">{"< 5s"}</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">Per Take</div>
          </div>
          <div className="hidden md:block w-px h-8 bg-[#1a2a3a]" />
          <div className="text-center">
            <div className="text-2xl font-bold text-white">∞</div>
            <div className="text-xs text-[#4dd9c0] uppercase tracking-wider mt-1">Topics Covered</div>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 pb-16 grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-10">

          {/* Trending Topics */}
          <section>
            <h2 className="font-serif text-2xl font-bold border-b-2 border-black pb-2 mb-4">Trending Topics</h2>
            <div className="flex flex-wrap gap-2">
              {TRENDING_TOPICS.map(t => (
                <button key={t} onClick={() => generate(t)}
                  className="px-4 py-2 text-sm font-semibold border border-gray-300 rounded-full bg-white hover:bg-[#1A1A1A] hover:text-white hover:border-[#1A1A1A] transition-colors">
                  {t}
                </button>
              ))}
            </div>
          </section>

          {/* What You Get */}
          <section>
            <h2 className="font-serif text-2xl font-bold border-b-2 border-black pb-2 mb-4">What You Get</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { icon: '🎯', title: 'Sharp Opinions', desc: "No wishy-washy both-sides fluff. Get a real, argued perspective you can agree with, debate, or steal for your next conversation." },
                { icon: '⚡', title: 'Instant Takes', desc: "Skip the 3,000-word think-pieces. Get the core argument in under 30 seconds, ready to share or spark a debate." },
                { icon: '🔄', title: 'Multiple Angles', desc: "Flip between Hot Take, Balanced, Devil's Advocate, and Contrarian. Same topic, totally different perspective." },
                { icon: '🧠', title: 'Genuinely Useful', desc: "Use takes to prep for debates, write essays, kick off conversations, or just understand all sides of an issue." },
              ].map(f => (
                <div key={f.title} className="bg-white border border-gray-200 rounded-xl p-5">
                  <div className="text-2xl mb-2">{f.icon}</div>
                  <h3 className="font-serif font-bold text-lg mb-1">{f.title}</h3>
                  <p className="text-sm text-gray-500">{f.desc}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Take Cards Promo */}
          <section className="bg-[#0d1117] rounded-2xl border border-[#1a2a3a] overflow-hidden">
            <div className="grid grid-cols-1 md:grid-cols-2">
              {/* Left: content */}
              <div className="p-6 md:p-8">
                <div className="flex items-center gap-2 mb-4">
                  <span className="text-xs font-bold uppercase tracking-widest text-[#4dd9c0]">New Feature</span>
                </div>
                <h2 className="font-serif text-3xl font-bold text-white leading-tight mb-3">
                  Turn takes into shareable cards 🎨
                </h2>
                <p className="text-[#8b949e] text-base leading-relaxed mb-6">
                  Generate beautiful 1080×1080 photo cards from any take — perfect for Instagram and X. Auto-matched photos, your branding, ready to post in seconds.
                </p>
                <div className="grid grid-cols-1 gap-3 mb-8">
                  {[
                    { icon: '📸', title: 'Auto photo', desc: 'Finds a relevant photo for your topic automatically.' },
                    { icon: '🎨', title: 'Branded design', desc: 'Every card includes Thought of View branding.' },
                    { icon: '⬇️', title: 'Download instantly', desc: 'One click to save as PNG and post anywhere.' },
                  ].map(f => (
                    <div key={f.title} className="flex items-start gap-3 bg-[#161b22] rounded-xl p-3 border border-[#21262d]">
                      <span className="text-lg mt-0.5">{f.icon}</span>
                      <div>
                        <p className="text-white font-semibold text-sm">{f.title}</p>
                        <p className="text-[#445566] text-xs leading-relaxed">{f.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
                <Link
                  href="/cards"
                  className="inline-block bg-[#4dd9c0] text-[#0d1117] font-bold px-8 py-3 rounded-xl hover:bg-teal-400 transition-colors text-sm uppercase tracking-wider"
                >
                  Create a Card — Free
                </Link>
              </div>

              {/* Right: rotating card preview */}
              <div className="hidden md:flex items-center justify-center p-6 bg-[#080d12]">
                <div style={{ width: '100%', maxWidth: 220, aspectRatio: '1/1', borderRadius: 12, overflow: 'hidden', border: '1px solid #21262d', position: 'relative', boxShadow: '0 0 40px rgba(77,217,192,0.1)' }}>
                  {CARD_EXAMPLES.map((card, i) => (
                    <div key={i} style={{ position: 'absolute', inset: 0, opacity: cardIndex === i ? 1 : 0, transition: 'opacity 0.8s ease' }}>
                      <div style={{ position: 'absolute', inset: 0, backgroundImage: `url(${card.photo})`, backgroundSize: 'cover', backgroundPosition: 'center' }} />
                      <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.45) 50%, rgba(0,0,0,0.85) 100%)' }} />
                      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: '#4dd9c0' }} />
                      <div style={{ position: 'absolute', inset: 0, padding: '14px 14px 40px' }}>
                        <div style={{ display: 'flex', gap: 6, marginBottom: 8, flexWrap: 'wrap' as const }}>
                          <span style={{ background: card.angleColor, color: '#fff', fontSize: 8, fontWeight: 700, padding: '3px 8px', borderRadius: 10, textTransform: 'uppercase' as const }}>{card.angleEmoji} {card.angle}</span>
                          <span style={{ background: 'rgba(77,217,192,0.2)', color: '#4dd9c0', fontSize: 8, fontWeight: 700, padding: '3px 8px', borderRadius: 10, textTransform: 'uppercase' as const }}>{card.topic}</span>
                        </div>
                        <p style={{ color: '#ffffff', fontSize: 10, fontWeight: 700, lineHeight: 1.4, marginBottom: 6, fontFamily: 'Georgia, serif', textShadow: '0 1px 4px rgba(0,0,0,0.8)' }}>{card.headline}</p>
                        <div style={{ height: 2, width: 24, background: '#4dd9c0', marginBottom: 6 }} />
                        <p style={{ color: 'rgba(255,255,255,0.75)', fontSize: 8, lineHeight: 1.6, textShadow: '0 1px 3px rgba(0,0,0,0.8)' }}>{card.body.slice(0, 110)}...</p>
                      </div>
                      <div style={{ position: 'absolute', bottom: 10, left: 0, right: 0, background: 'rgba(0,0,0,0.8)', padding: '6px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ color: '#ffffff', fontSize: 8, fontWeight: 700, fontFamily: 'Georgia, serif' }}>Thought <span style={{ color: '#4dd9c0' }}>of View</span></span>
                        <span style={{ color: '#445566', fontSize: 7 }}>thoughtofview.com</span>
                      </div>
                      <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 2, background: '#4dd9c0' }} />
                    </div>
                  ))}
                  {/* Dot indicators */}
                  <div style={{ position: 'absolute', bottom: 22, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 4, zIndex: 10 }}>
                    {CARD_EXAMPLES.map((_, i) => (
                      <div key={i} onClick={() => setCardIndex(i)} style={{ width: cardIndex === i ? 16 : 6, height: 6, borderRadius: 3, background: cardIndex === i ? '#4dd9c0' : 'rgba(255,255,255,0.3)', cursor: 'pointer', transition: 'all 0.3s ease' }} />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Take Battle Promo */}
          <section className="rounded-2xl overflow-hidden border border-[#1a2a3a] relative">
            {/* Arena background */}
            <div style={{
              position: 'absolute', inset: 0,
              backgroundImage: "url('/arena-bg.png')",
              backgroundSize: 'cover', backgroundPosition: 'center',
              opacity: 0.4,
            }} />
            <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.75) 100%)' }} />
            <div className="relative z-10 p-6 md:p-8">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-xs font-bold uppercase tracking-widest text-[#e85d3a]">⚔️ Live AI Debate</span>
              </div>
              <h2 className="font-serif text-3xl font-bold text-white leading-tight mb-3">
                Take Battle
              </h2>
              <p className="text-[#ccc] text-base leading-relaxed mb-6 max-w-lg">
                Watch two AI perspectives go head-to-head on any topic. Pick your fighters, start the battle, and see who wins. Hot Take vs Devil's Advocate. Contrarian vs Expert Analysis. Winner takes all.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
                {[
                  { icon: '⚔️', title: 'Live debate', desc: '4 rounds of AI arguing back and forth in real time.' },
                  { icon: '🏆', title: 'AI judge', desc: 'An AI judge declares the winner after the final round.' },
                  { icon: '🎯', title: 'Any topic', desc: 'Politics, tech, finance, culture — anything goes.' },
                ].map(f => (
                  <div key={f.title} className="bg-black/40 rounded-xl p-4 border border-white/10">
                    <div className="text-xl mb-2">{f.icon}</div>
                    <p className="text-white font-semibold text-sm mb-1">{f.title}</p>
                    <p className="text-[#aaa] text-xs leading-relaxed">{f.desc}</p>
                  </div>
                ))}
              </div>
              <Link
                href="/battle"
                className="inline-block bg-[#e85d3a] text-white font-bold px-8 py-3 rounded-xl hover:bg-orange-700 transition-colors text-sm uppercase tracking-wider"
              >
                ⚔️ Start a Battle — Free
              </Link>
            </div>
          </section>

          {/* Featured Takes */}
          {featuredTakes.length > 0 && (
            <section>
              <div className="flex items-center justify-between border-b-2 border-black pb-2 mb-4">
                <h2 className="font-serif text-2xl font-bold">Top Takes</h2>
                <Link href="/feed" className="text-xs font-bold text-brand-orange hover:underline uppercase tracking-wider">
                  View all →
                </Link>
              </div>
              <div className="space-y-4">
                {featuredTakes.map(take => (
                  <div key={take.id} className="bg-white border border-gray-200 rounded-xl p-5 hover:border-[#4dd9c0]/40 transition-colors">
                    <div className="flex gap-2 mb-3 flex-wrap">
                      <span className="text-xs bg-[#0d1117] text-[#4dd9c0] px-3 py-1 rounded-full uppercase tracking-wider font-medium">
                        {take.topic}
                      </span>
                      <span className={`text-xs text-white px-3 py-1 rounded-full uppercase tracking-wider font-medium ${ANGLE_COLORS[take.angle] || 'bg-gray-500'}`}>
                        {ANGLE_ICONS[take.angle]} {take.angle}
                      </span>
                    </div>
                    <h3 className="font-serif font-bold text-lg mb-2 leading-snug">{take.headline}</h3>
                    <p className="text-sm text-gray-500 line-clamp-2 mb-3">{take.body}</p>
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-gray-400 flex items-center gap-1">
                        <span>▲</span> {take.upvotes || 0} upvotes
                      </span>
                      <Link href="/feed" className="text-xs text-brand-orange hover:underline font-medium">
                        Discuss →
                      </Link>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* OpinionBot Promo */}
          <section className="bg-[#1A1A1A] rounded-2xl p-6 md:p-8 border border-[#2a2a2a]">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-xs font-bold uppercase tracking-widest text-brand-orange">Desktop App</span>
            </div>
            <h2 className="font-serif text-3xl md:text-4xl font-bold text-white leading-tight mb-3">
              Meet OpinionBot 🤖
            </h2>
            <p className="text-[#aaa] text-base leading-relaxed mb-6 max-w-lg">
              Get AI-powered hot takes, balanced analysis, and contrarian views — right from your desktop. No browser needed. OpinionBot sits in your taskbar, ready whenever you need a sharp perspective.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
              {[
                { icon: '⚡', title: 'Instant access', desc: 'One click from your taskbar — no loading, no tabs.' },
                { icon: '🖥️', title: 'Works offline', desc: 'Generate takes without switching away from your work.' },
                { icon: '🪟', title: 'Windows & Mac', desc: 'Native desktop app for both platforms.' },
              ].map(f => (
                <div key={f.title} className="bg-[#2A2A2A] rounded-xl p-4">
                  <div className="text-xl mb-2">{f.icon}</div>
                  <p className="text-white font-semibold text-sm mb-1">{f.title}</p>
                  <p className="text-[#888] text-xs leading-relaxed">{f.desc}</p>
                </div>
              ))}
            </div>
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
              <a
                href="/opinionbot"
                className="bg-brand-orange text-white font-bold px-8 py-3 rounded-xl hover:bg-orange-700 transition-colors text-sm uppercase tracking-wider"
              >
                Get OpinionBot — $4.99
              </a>
              <span className="text-[#666] text-xs">One-time purchase · No subscription required</span>
            </div>
          </section>

          {/* Recommended Reads */}
          <section>
            <h2 className="font-serif text-2xl font-bold border-b-2 border-black pb-2 mb-1">Recommended Reads</h2>
            <p className="text-xs text-gray-400 mb-4">Books that'll sharpen your thinking. <em>(Affiliate links — we may earn a commission.)</em></p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {BOOKS.map(b => (
                <div key={b.title} className="bg-white border border-gray-200 rounded-xl p-5 flex flex-col gap-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-yellow-600">{b.tag}</span>
                  <h4 className="font-serif font-bold text-lg leading-tight">{b.title}</h4>
                  <p className="text-xs text-gray-500 flex-1">{b.desc}</p>
                  <a href={b.link} target="_blank" rel="noopener sponsored"
                    className="text-xs font-bold uppercase tracking-wider text-brand-orange hover:underline">
                    View on Amazon →
                  </a>
                </div>
              ))}
            </div>
          </section>

          {/* Tools */}
          <section>
            <h2 className="font-serif text-2xl font-bold border-b-2 border-black pb-2 mb-1">Tools for Deep Thinkers</h2>
            <p className="text-xs text-gray-400 mb-4"><em>(Affiliate partnerships — we may earn a commission at no extra cost to you.)</em></p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {TOOLS.map(t => (
                <div key={t.title} className="bg-white border border-gray-200 rounded-xl p-5 flex flex-col gap-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-yellow-600">{t.tag}</span>
                  <h4 className="font-serif font-bold text-lg leading-tight">{t.title}</h4>
                  <p className="text-xs text-gray-500 flex-1">{t.desc}</p>
                  <a href={t.link} target="_blank" rel="noopener sponsored"
                    className="text-xs font-bold uppercase tracking-wider text-brand-orange hover:underline">
                    {t.cta}
                  </a>
                </div>
              ))}
            </div>
          </section>

          {/* FAQ Section */}
          <section>
            <div className="flex items-center justify-between border-b-2 border-black pb-2 mb-4">
              <h2 className="font-serif text-2xl font-bold">Common Questions</h2>
              <Link href="/faq" className="text-xs font-bold text-brand-orange hover:underline uppercase tracking-wider">
                Full FAQ →
              </Link>
            </div>
            <div className="space-y-2">
              {HOME_FAQS.map((faq, i) => (
                <div key={i} className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                  <button
                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                    className="w-full flex items-center justify-between px-5 py-4 text-left font-medium text-sm hover:bg-gray-50 transition-colors"
                  >
                    <span>{faq.q}</span>
                    <span className="text-gray-400 ml-4 shrink-0">{openFaq === i ? '▲' : '▼'}</span>
                  </button>
                  {openFaq === i && (
                    <div className="px-5 pb-4 text-sm text-gray-600 leading-relaxed border-t border-gray-100 pt-3">
                      {faq.a}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>

        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <div className="bg-[#1c1a16] rounded-xl p-5">
            <h3 className="font-serif text-lg font-bold text-[#f0ede6] mb-1">Daily Takes — Free</h3>
            <p className="text-xs text-[#b0ac9f] mb-4">Get 3 sharp AI perspectives on today's biggest topics. No fluff, no spam.</p>
            <form action="https://dc090f69.sibforms.com/serve/MUIFAJgWdUk-T8_WFwc7NtbcuIW5Y3wZKv7LUr6qcOf5S2yCVf4IbBcGOUEPjtQqPW32qkJLcwQK_wjuYTRAaYAcAbXt8pCjZNS20EgCyx4vrWSuRxrGl-7nARl48iWf3WfikOKMA4k3qeRJ_oCNCDobsawb9tGQE-EKz5mHsOsKbPxAOCEAuin9I_KvKXekjGlOPH1iFFx4n1qhYg==" method="POST">
              <input type="email" name="EMAIL" placeholder="your@email.com" required
                className="w-full px-3 py-2 text-sm rounded-lg bg-[#2a2824] text-[#f0ede6] border border-[#444] mb-2 outline-none focus:border-brand-orange" />
              <button type="submit"
                className="w-full py-2 text-sm font-bold uppercase tracking-wider bg-yellow-400 text-[#1a1500] rounded-lg hover:bg-yellow-300 transition-colors">
                Subscribe Free
              </button>
              <p className="text-xs text-[#666] mt-2">Unsubscribe anytime. We don't sell your data.</p>
              <input type="hidden" name="locale" value="en" />
              <input type="hidden" name="html_type" value="simple" />
            </form>
          </div>

          <div className="bg-white rounded-xl p-5 border border-gray-100">
            <h3 className="font-serif text-lg font-bold border-b-2 border-black pb-2 mb-4">Popular Takes</h3>
            <ul className="space-y-3">
              {[
                'AI will replace most creative jobs by 2030',
                'Social media is making us measurably dumber',
                'Remote work wins on productivity — the data is in',
                "Bitcoin will hit $1M. Here's why skeptics are wrong.",
                'College degrees are no longer worth the cost',
              ].map((title, i) => (
                <li key={i} className="flex gap-3 cursor-pointer group" onClick={() => generate(title)}>
                  <span className="text-xs font-bold text-gray-300 mt-0.5 shrink-0">0{i+1}</span>
                  <span className="text-sm font-medium group-hover:text-brand-orange transition-colors">{title}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-[#0d1117] rounded-xl p-5 border border-[#1a2a3a]">
            <p className="text-xs font-bold uppercase tracking-widest text-[#e85d3a] mb-2">Go Premium</p>
            <h4 className="font-serif text-base font-bold text-white mb-2">Unlimited takes. No ads.</h4>
            <p className="text-xs text-[#8b949e] leading-relaxed mb-4">Remove limits and get the full Thought of View experience for $5/month.</p>
            <Link href="/premium"
              className="block w-full bg-[#e85d3a] text-white text-xs font-bold px-4 py-2.5 rounded-lg text-center hover:bg-orange-700 transition-colors uppercase tracking-wider">
              Upgrade — $5/mo
            </Link>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-300 bg-[#F0EDE6] py-8 px-4 text-center">
        <a href="/" className="font-serif text-2xl font-bold mb-4 inline-block">Thought<span className="text-brand-orange">of</span>View</a>
        <div className="flex justify-center gap-6 text-xs text-gray-500 mb-4 flex-wrap">
          <a href="/about" className="hover:text-black">About</a>
          <a href="/faq" className="hover:text-black">FAQ</a>
          <a href="/battle" className="hover:text-black">Battle</a>
          <a href="/cards" className="hover:text-black">Cards</a>
          <a href="/privacy" className="hover:text-black">Privacy Policy</a>
          <a href="/terms" className="hover:text-black">Terms of Use</a>
          <a href="/contact" className="hover:text-black">Contact</a>
          <a href="/advertise" className="hover:text-black">Advertise</a>
        </div>
        <p className="text-xs text-gray-400">
          © 2026 ThoughtofView.com · AI-generated content for entertainment and informational purposes.<br />
          This site contains affiliate links and advertising. <a href="/disclosure" className="underline">Disclosure</a>.
        </p>
      </footer>

      <div id="cookie-banner" className="fixed bottom-0 left-0 right-0 bg-[#1A1A1A] text-white text-sm px-4 py-3 flex items-center justify-between gap-4 z-50">
        <p>We use cookies for ads and analytics. <a href="/privacy" className="underline text-yellow-400">Learn more</a>.</p>
        <button onClick={() => { document.getElementById('cookie-banner')!.style.display='none'; localStorage.setItem('cookies_ok','1') }}
          className="bg-brand-orange text-white text-xs font-bold px-4 py-2 rounded-full whitespace-nowrap">
          Accept & Continue
        </button>
      </div>
    </div>
  )
}
