import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about Thought of View — the AI-powered opinion platform.',
}

const FAQS = [
  {
    category: 'Getting Started',
    items: [
      {
        q: 'What is Thought of View?',
        a: 'Thought of View is an AI-powered opinion platform. Enter any topic — politics, tech, finance, culture, sports — and get instant, sharp perspectives from five different angles: Hot Take, Balanced, Devil\'s Advocate, Contrarian, and Expert Analysis.',
      },
      {
        q: 'Is it free to use?',
        a: 'Yes — Thought of View is free to use. Free accounts get 5 takes per day across all angles. Premium members ($5/month) get unlimited takes, no ads, and priority generation.',
      },
      {
        q: 'Do I need an account?',
        a: 'No account is needed to generate takes. However, signing in with Google lets you save your takes to the public feed, upvote others\' takes, and leave comments.',
      },
      {
        q: 'How do I sign in?',
        a: 'Click "Sign in" in the top navigation bar. We use Google sign-in — no password required.',
      },
    ],
  },
  {
    category: 'The AI Takes',
    items: [
      {
        q: 'How are the takes generated?',
        a: 'Takes are generated by large language models (LLMs) via the Groq API. Each angle — Hot Take, Balanced, Devil\'s Advocate, Contrarian, Expert Analysis — is prompted differently to produce a distinct perspective on your topic.',
      },
      {
        q: 'Are the takes accurate?',
        a: 'Takes are designed to be sharp, opinionated perspectives — not factual summaries. They\'re great for sparking debate, understanding different viewpoints, or getting quick arguments for and against a position. Always verify facts independently before citing them.',
      },
      {
        q: 'What topics can I generate takes on?',
        a: 'Virtually anything — politics, technology, finance, culture, sports, philosophy, business, relationships, and more. The more specific your topic, the sharper the take.',
      },
      {
        q: 'What are the five angles?',
        a: 'Hot Take: a bold, provocative stance. Balanced: a fair, both-sides view. Devil\'s Advocate: argues the opposite of the obvious position. Contrarian: challenges the mainstream narrative. Expert Analysis: a deep-dive, informed perspective.',
      },
      {
        q: 'Why do takes sometimes seem one-sided?',
        a: 'By design — each angle is meant to argue a specific position, not hedge. The Balanced angle is the exception. Use multiple angles on the same topic to get a full picture.',
      },
    ],
  },
  {
    category: 'The Feed',
    items: [
      {
        q: 'What is the Feed?',
        a: 'The Feed is a public community page where signed-in users\' takes are automatically shared. You can browse, upvote, comment on, and share takes from the community.',
      },
      {
        q: 'Why isn\'t my take showing in the Feed?',
        a: 'Takes are only saved to the Feed if you\'re signed in when you generate them. Sign in with Google, then generate a take — it will appear in the Feed automatically.',
      },
      {
        q: 'Can I delete my takes?',
        a: 'Currently takes can\'t be deleted from the feed directly. If you need a take removed, contact us at thoughtofview@gmail.com.',
      },
    ],
  },
  {
    category: 'Premium & Payments',
    items: [
      {
        q: 'What does Premium include?',
        a: 'Premium gives you unlimited takes per day, no ads, and priority generation speed. It\'s $5/month, billed monthly, and you can cancel anytime.',
      },
      {
        q: 'How do I upgrade to Premium?',
        a: 'Visit the Premium page and click "Upgrade Now." You\'ll be directed to a secure Stripe checkout. Once payment is complete, your account is upgraded instantly.',
      },
      {
        q: 'How do I cancel my subscription?',
        a: 'Go to your Profile page and click "Cancel Subscription." Your Premium access continues until the end of the current billing period.',
      },
      {
        q: 'Is my payment secure?',
        a: 'Yes. All payments are processed by Stripe, one of the world\'s most trusted payment platforms. We never store your card details.',
      },
      {
        q: 'Do you offer refunds?',
        a: 'All purchases are final. If you have an issue, contact us at thoughtofview@gmail.com and we\'ll do our best to help.',
      },
    ],
  },
  {
    category: 'OpinionBot',
    items: [
      {
        q: 'What is OpinionBot?',
        a: 'OpinionBot is a native desktop app for Windows and Mac. It lives in your taskbar and lets you generate AI takes on any topic without opening a browser — perfect for researchers, writers, and debaters who want instant perspectives while working.',
      },
      {
        q: 'How much does OpinionBot cost?',
        a: 'OpinionBot is a one-time purchase of $4.99. No subscription required.',
      },
      {
        q: 'Is OpinionBot the same as a Premium subscription?',
        a: 'No — they\'re separate products. Premium is a monthly subscription for the website. OpinionBot is a standalone desktop app. You can have either, both, or neither.',
      },
      {
        q: 'Which operating systems does OpinionBot support?',
        a: 'OpinionBot is available for Windows and Mac.',
      },
    ],
  },
  {
    category: 'Privacy & Data',
    items: [
      {
        q: 'What data do you collect?',
        a: 'We collect your email address and name when you sign in via Google. We store takes you generate while signed in. We use cookies for analytics and advertising. See our Privacy Policy for full details.',
      },
      {
        q: 'Do you sell my data?',
        a: 'No. We never sell personal data to third parties.',
      },
      {
        q: 'How do I delete my account?',
        a: 'Email us at thoughtofview@gmail.com and we\'ll delete your account and associated data.',
      },
    ],
  },
]

export default function FAQPage() {
  return (
    <main style={{ minHeight: '100vh', backgroundColor: '#0d1117', color: '#e6edf3', fontFamily: 'system-ui, sans-serif' }}>

      {/* Header */}
      <div style={{ borderBottom: '1px solid #1a2a3a' }}>
        <div style={{ maxWidth: '760px', margin: '0 auto', padding: '80px 24px 48px' }}>
          <p style={{ color: '#4dd9c0', fontSize: '13px', fontWeight: 600, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '16px' }}>
            Help Center
          </p>
          <h1 style={{ fontSize: '48px', fontWeight: 700, lineHeight: 1.15, margin: '0 0 16px', color: '#ffffff' }}>
            Frequently Asked Questions
          </h1>
          <p style={{ fontSize: '18px', color: '#8b949e', margin: 0, lineHeight: 1.6 }}>
            Everything you need to know about Thought of View, Premium, and OpinionBot.
          </p>
        </div>
      </div>

      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '56px 24px 80px' }}>

        {FAQS.map(({ category, items }) => (
          <div key={category} style={{ marginBottom: '56px' }}>
            <h2 style={{ fontSize: '13px', fontWeight: 700, color: '#4dd9c0', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '24px', paddingBottom: '12px', borderBottom: '1px solid #1a2a3a' }}>
              {category}
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
              {items.map(({ q, a }) => (
                <div key={q}>
                  <h3 style={{ fontSize: '17px', fontWeight: 600, color: '#ffffff', margin: '0 0 8px' }}>{q}</h3>
                  <p style={{ fontSize: '15px', color: '#8b949e', lineHeight: 1.8, margin: 0 }}>{a}</p>
                </div>
              ))}
            </div>
          </div>
        ))}

        {/* Still have questions */}
        <div style={{ backgroundColor: '#161b22', borderRadius: '16px', padding: '32px', border: '1px solid #1a2a3a', textAlign: 'center' }}>
          <h3 style={{ fontSize: '20px', fontWeight: 600, color: '#ffffff', margin: '0 0 8px' }}>Still have questions?</h3>
          <p style={{ fontSize: '15px', color: '#8b949e', margin: '0 0 20px' }}>
            Can't find the answer you're looking for? We're happy to help.
          </p>
          <a
            href="mailto:thoughtofview@gmail.com"
            style={{ display: 'inline-block', backgroundColor: '#e85d3a', color: '#ffffff', fontWeight: 700, padding: '12px 28px', borderRadius: '10px', textDecoration: 'none', fontSize: '14px', letterSpacing: '0.05em', textTransform: 'uppercase' }}
          >
            Contact Us
          </a>
        </div>

      </div>
    </main>
  )
}
